udating-Db
Trycatch-tv/team15-project6-smartclassroom-api pull request #42
Opened 2023-04-25 21:34 UTC by joshArfDev

Actualicé lo requerido y modifiqué unos controllers para el funcionamiento de la api.

2023-04-25 22:13 UTC, luisdavid0202 requested changes
además de los otros comentarios, asegurate que las configuraciones de las tablas en el script de la bd hagan match con las configuraciones de los models

2023-04-25 22:13 UTC, luisdavid0202 commented on db/init-db.sql
> +    `student_id` INT DEFAULT NULL,
aquí sobra el default

2023-04-25 22:13 UTC, luisdavid0202 commented on db/init-db.sql
> +    `student_id` INT DEFAULT NULL,
y debería ser NOT NULL

2023-04-25 22:13 UTC, luisdavid0202 commented on db/init-db.sql
> +    `course_id` INT DEFAULT NULL,
sobra el default y debería ser NOT NULL

2023-04-25 22:13 UTC, luisdavid0202 commented on db/init-db.sql
> +    `cancellation_date` DATE NOT NULL
aquí debería poder aceptar NULL

2023-04-25 22:13 UTC, luisdavid0202 commented on db/init-db.sql
> +    `grade5` FLOAT(2.2) NOT NULL
todas las notas deberían poder ser NULL

2023-04-25 22:13 UTC, luisdavid0202 commented on db/init-db.sql
> +    `grade5` FLOAT(2.2) NOT NULL
O las puedes dejar NOT NULL pero con valor DEFAULT en 0

2023-04-25 22:13 UTC, luisdavid0202 commented on db/init-db.sql
> +UNIQUE (student_id, course_id, registration_date);
esto sobra

2023-04-25 22:13 UTC, luisdavid0202 commented on api/controllers/grades.js
> +    console.error(err)
Esto no va

2023-04-25 22:13 UTC, luisdavid0202 commented on api/controllers/registrations.js
> +    const { student_id, course_id, registration_date, cancellation_date } = req.body
aquí los únicos parámetros que deberíamos recibir son el student_id y el course_id, el registration_date lo sacamos con la hora actual del servidor y el cancellation_date debería ser null

2023-04-25 22:13 UTC, luisdavid0202 commented on api/controllers/registrations.js
>        return
esto está bien?

2023-04-25 22:13 UTC, luisdavid0202 commented on api/controllers/registrations.js
> +        cancellation_date
aquí sobran estos 2 campos

2023-04-25 22:13 UTC, luisdavid0202 commented on api/controllers/registrations.js
> +      cancellation_date: cancellation_date
este va null

2023-04-25 22:13 UTC, luisdavid0202 commented on api/controllers/registrations.js
> +      registration_date: registration_date,
el registration date deberías calcularlo en el server, algo como `const fechaActual = new Date();`

2023-04-26 04:06 UTC, joshArfDev commented on api/controllers/registrations.js
>        return
Lo hice para que no hubiera necesidad de llegar al course da abajo, así se "finalizaría" la petición de una vez. Que piensas?

2023-04-26 20:40 UTC, luisdavid0202 approved these changes

2023-04-26 20:40 UTC, merged